apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: simple-db-rest
  name: simple-db-rest-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-db-rest
    spec:
      containers:
        - image: simple-db-rest:1.0
          #use imagePullPolicy: IfNotPresent in prod
          #use imagePullPolicy: Always in development
          imagePullPolicy: Never
          name: simple-db-rest
          ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-db-rest-service
  name: simple-db-rest-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30100
    targetPort: 8080
  selector:
    app: simple-db-rest


